# Generated by Django 4.2.1 on 2023-05-14 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesystem_name', models.UUIDField()),
                ('status', models.BooleanField(default=True)),
                ('name', models.TextField()),
                ('created', models.DateField(default=datetime.datetime(2023, 5, 14, 11, 45, 17, 278286))),
                ('template', models.TextField(default='')),
            ],
            options={
                'db_table': 'environment',
            },
        ),
    ]
