# Generated by Django 4.2.1 on 2023-05-15 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 17, 34, 29, 592476)),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_name', models.UUIDField()),
                ('created', models.DateField(default=datetime.datetime(2023, 5, 15, 17, 34, 29, 592767))),
                ('environment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.environment')),
            ],
            options={
                'db_table': 'snapshot',
            },
        ),
    ]
