# Generated by Django 4.2.1 on 2023-05-15 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_environment_created_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 18, 47, 7, 58667)),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 18, 47, 7, 58959)),
        ),
    ]
