# Generated by Django 4.2.1 on 2023-05-15 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_environment_created_alter_snapshot_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='last',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 18, 56, 13, 154851)),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 18, 56, 13, 155149)),
        ),
    ]
