name: Danix File System

on: 
  pull_request:
    branches: [main]
  push:
    branches: [dev]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      
      - name: Install danix
        run: |
          sudo apt update -y
          sudo apt install make -y
          cd danix
          sudo mv ./registry.py /usr/local/lib/python$(python --version 2>&1 | awk '{print $2}' | cut -d'.' -f1,2)/dist-packages/django/apps/registry.py
          sudo make install
          sudo make aliases
          sudo danix

